<?php 
echo js('proj4js/proj4js-compressed');
echo js('OpenLayers-2.8/lib/OpenLayers');
echo js('maps/show/show');
?>
<link rel="stylesheet" href="<?php echo css('neatline'); ?>" />

<script type="text/javascript"><?php echo $params['proj4js'] ?></script>

<div id="tmp" class="themap"></div>
<script type="text/javascript">
		if (typeof (Omeka) == 'undefined') {
			Omeka = new Object();
		}
		
		if (!Omeka.NeatlineMaps) {
			Omeka.NeatlineMaps = new Array();
		}

		if (!Omeka.NeatlineMaps.history) {
			Omeka.NeatlineMaps.history = new Array();
		}
		NLconfig = new Object();
//<!--
	<?php foreach ($params as $name => $value) {
			echo 'tmp' . "$name = '$value';"	;
			$layers = $params['layers'];
		}
		?>NLconfig.backgroundlayers = new Array();<?php
		foreach (array_keys($layers) as $layername) {
			$layerinfo = $layers[$layername];
		  	?>
		  	NLconfig.backgroundlayers.push(
				  	new OpenLayers.Layer.WMS('<?php echo $layerinfo[1]; ?>' , '<?php echo $layerinfo[0];?>', {layers: '<?php echo $layername; ?>'})
				  	);
		  	<?php 
	 	 } 	
		?>
		NLconfig.bbox = new OpenLayers.Bounds(NLconfig.minx,NLconfig.miny,NLconfig.maxx,NLconfig.maxy);

		NLconfig.mapdiv = "map" + Omeka.NeatlineMaps.length;
		document.getElementById('tmp').id = NLconfig.mapdiv;	
		init(NLconfig);
		Omeka.NeatlineMaps.history[Omeka.NeatlineMaps.history.length] = NLconfig;
		delete(NLconfig);
//-->

</script>
