<?php 
echo js('proj4js/proj4js-compressed');
echo js('maps/show/show');
?>
<script type="text/javascript" src="http://openlayers.org/api/OpenLayers.js"> </script>
<link rel="stylesheet" href="<?php echo css('neatline'); ?>" />
<script type="text/javascript"><?php echo $params['proj4js'] ?></script>
<div id="addlayerdialog">
<div id="mappreview"></div>
<?php

$items = get_items(array('type' => neatlinemaps_getMapItemType() ), 200);
$itemnames = array();
$itemids = array();
foreach ($items as $item) {
	array_push($itemnames,item("Dublin Core", "Title", array(), $item));
	array_push($itemids,$item->id);
}
$options = array_combine($itemids,$itemnames);
echo $this->formSelect("layerselect", reset($options), array('class'=>'select'), $options);
?>
</div>
<div id="NLtmp" class="themap"></div>
<script type="text/javascript">
		if (typeof (Omeka) == 'undefined') {
			Omeka = new Object();
		}
		
		if (!Omeka.NeatlineMaps) {
			Omeka.NeatlineMaps = new Array();
		}

		if (!Omeka.NeatlineMaps.history) {
			Omeka.NeatlineMaps.history = new Array();
		}
		NLconfig = new Object();
//<!--
	<?php foreach ($params as $name => $value) {
			echo 'NLconfig.' . "$name = '$value';"	;
			$layers = $params['layers'];
		}
		?>NLconfig.backgroundlayers = new Array();<?php
		foreach (array_keys($layers) as $layername) {
			$layerinfo = $layers[$layername];
		  	?>
		  	NLconfig.backgroundlayers.push(
				  	new OpenLayers.Layer.WMS('<?php echo $layerinfo[1]; ?>' , '<?php echo $layerinfo[0];?>', {layers: '<?php echo $layername; ?>'})
				  	);
		  	<?php 
	 	 } 	
		?>
		NLconfig.bbox = new OpenLayers.Bounds(NLconfig.minx,NLconfig.miny,NLconfig.maxx,NLconfig.maxy);
		Omeka.NeatlineMaps.history[Omeka.NeatlineMaps.history.length] = NLconfig;
		NLconfig.mapdiv = "map" + Omeka.NeatlineMaps.history.length;
		document.getElementById('NLtmp').id = NLconfig.mapdiv;	
		Event.observe(window, 'load', Omeka.NeatlineMaps.createMap.bindAsEventListener(this,NLconfig));
		delete(NLconfig);
//-->

</script>
