<?php

$items = get_items(array('type' => neatlinemaps_getMapItemType() ), 200);
$itemnames = array();
$itemids = array();
foreach ($items as $item) {
	array_push($itemnames,item("Dublin Core", "Title", array(), $item));
	array_push($itemids,$item->id);
	
}
$options = array_combine($itemnames,$itemids);
?>

<div id="backgroundtext"><?php echo $this->formSelect( $inputNameStem . "[text]", $value, array('class'=>'select'), $options); ?>
</div>
